### ISSUE TITLE
Param since_id of api /user/dashboard is not working correctly.

### ISSUE THREAD

**Issue by jaggerwang** [tumblr/tumblr.go#11]
The posts returned by api `/user/dashboard` ordered by id desc, but if given `since_id` param, the server will return posts bigger than `since_id`, it should return posts little than `since_id`.

**Comment by jasonpenny** [comment]
I disagree, I would expect `since_id` to return posts bigger than the id specified, since they are newer;
if we're talking about time and it's 10:30 and you ask for hours since 7:00, I would expect a response of 8, 9 and 10.

But, more importantly, this is not really an issue for `tumblr.go`, since `tumblr.go` just uses the Tumblr API.
If you want to discuss API decisions, so you can go to https://groups.google.com/group/tumblr-api/ to send an email message to the group.

**Comment by jaggerwang** [comment]
OK, I'll submit to the group. Anyway the fact is, given the last `since_id` of the last page, can not get the next page, it's same as the last page.

**Comment by jaggerwang** [comment]
Found a param `before_id` which not documented in Tumblr official group [post](https://groups.google.com/forum/#!searchin/tumblr-api/since_id%7Csort:date/tumblr-api/STUcJXqMpsI/kLnkTo8XfkkJ), and submitted a pull request #12 .
